name: customer
description: customer app for heryerpark
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_auth: 4.2.5
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  firebase_messaging: ^14.2.1
  firebase_analytics: ^10.1.0
  flutter_local_notifications: ^13.0.0

  provider: ^6.0.5
  get_it: ^7.2.0
  http: ^0.13.5
  intl: ^0.17.0
  geolocator: ^9.0.2
  get: ^4.6.5
  dart_ipify: ^1.1.1
  google_maps_flutter: ^2.2.4

  package_info_plus: ^3.0.2
  shared_preferences: ^2.0.17
  cached_network_image: ^3.2.3
  flutter_tawk: ^0.1.0
  webview_flutter: ^3.0.1
  flutter_widget_from_html: ^0.9.1
  image_picker: ^0.8.6+1
  flutter_rating_bar: ^4.0.1
  widget_to_marker: ^1.0.3

  google_fonts: ^4.0.1
  flex_color_scheme: ^6.1.2
  flutter_feather_icons: ^2.0.0+1
  material_design_icons_flutter: ^6.0.7096
  cupertino_icons: ^1.0.5
  line_icons: ^2.0.1

  google_nav_bar: ^5.0.6
  coupon_uikit: ^0.2.0
  carousel_slider: ^4.2.1
  qr_flutter: ^4.0.0
  pin_code_fields: ^7.4.0
  flutter_countdown_timer: ^4.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/map.json
    - assets/mapdark.json